#pragma once

#ifndef BUTTON_ACTION_H
#define BUTTON_ACTION_H

enum ButtonAction {
    BUTTON_PLAY_LOCAL,
    BUTTON_PLAY_ONLINE,
    BUTTON_VAMOS,
    BUTTON_SHOP,
    BUTTON_CAR_COLLECTION,
    BUTTON_OPTIONS,
    BUTTON_EXIT,
    BUTTON_BACK,
    BUTTON_VIDEO,
    BUTTON_SONIDO,
    BUTTON_1080,
    BUTTON_720,
    BUTTON_FULLSCREEN,
    BUTTON_WINDOW,
    BUTTON_APLICAR,
    BUTTON_C1,
    BUTTON_C2,
    BUTTON_C3,
    BUTTON_SLIDER1,
    BUTTON_SLIDER2,
    BUTTON_SLIDER3,
    BUTTON_UNKNOWN
};

#endif // BUTTON_ACTION_H